### ISSUE TITLE
Bind assemblers by interface

### ISSUE THREAD

**Issue by adrienlauer** [seedstack/business#10]
Assemblers should be bound by interfaces instead of by implementation class. It will be cleaner for projects to inject the interface (no more do... methods called) and will resolve problems with the DSL.

**Comment by pith** [comment]
Things to do in order to solve this:
- [x] Remove the third type parameter of Assembler<?,?,?>
- [x] Bind the `Assembler` interface to assemblers implementations
- [x] Add tests on the DSL `InternalRegistry`
