### ISSUE TITLE
Provide more semantic in the aggregate events API

### ISSUE THREAD

**Issue by pith** [seedstack/business#2]
**Context:**
Annotating methods with `@Read`, `@Persist` or `@Delete` enable AOP to fire aggregate events. These events contains the aggregate root class and the invocation context (the method called and its arguments).

``` java
@Read
AGGREGATE load(KEY id);

@Delete
void delete(AGGREGATE aggregate);

@Persist
void persist(AGGREGATE aggregate);
```

``` java
public abstract class BaseAggregateEvent extends DomainEvent {

    private final Class<? extends AggregateRoot<?>> aggregateRoot;

    private final Context context;

    public BaseAggregateEvent(Method methodCalled, Object[] args, Class<? extends AggregateRoot<?>> aggregateRoot) {
        this.context = new Context(methodCalled, args.clone());
        this.aggregateRoot = aggregateRoot;
    }

    /* getters - setters */

    public final class Context {

        private final Object[] args;

        private final Method methodCalled;

        private Context(Method methodCalled, Object[] args) {
            this.methodCalled = methodCalled;
            this.args = args.clone();
        }

        /* getters - setters */
    }
}
```

``` java
public class AggregatePersistedEvent extends BaseAggregateEvent {

    public AggregatePersistedEvent(Method methodCalled, Object[] args, Class<? extends AggregateRoot<?>> aggregateRoot) {
        super(methodCalled, args, aggregateRoot);
    }
}
```

**Improvement:**
An idea would be to place the annotation on the parameter in order to provide more information in the API. Currently when you receive a persisted event, if you want to get the persisted aggregate, we have to iterate over the method arguments contained in the context and find the one which matches the aggregate root class. By placing the `@Persist` on the `aggregate` parameter we could initialize the event directly with the aggregate instance instead of providing a context (which BTW create a direct binding between the event sent and the sender).

**After change:**

``` java
void persist(@Persist AGGREGATE aggregate);
```

``` java
public class AggregatePersistedEvent extends BaseAggregateEvent {

    public AggregatePersistedEvent(AggregateRoot<?> aggregateRoot) { ... }

    public AggregateRoot<?> getAggregateRoot(){ ... }
}
```

**Comment by adrienlauer** [comment]
Those annotations are too generic to be useful from a DDD perspective and have been removed.
