### ISSUE TITLE
Support qualifiers in the assembler DSL

### ISSUE THREAD

**Issue by pith** [seedstack/business#22]
Add the  API and implementation for qualifiers as specified in the PEP.

**Comment by pith** [comment]
Qualifiers are now supported for assemblers but not for repositories and factories.

**Comment by adrienlauer** [comment]
Example:

```
order = merge(orderDto).to(Order.class)
    .with(ModelMapper.class)
    .fromRepository("myQualifier")
    .thenFromFactory("otherQualifier");
```

**Comment by pith** [comment]
Wow that's an old ticket :)

**Comment by adrienlauer** [comment]
@pith Hello Pith! Just saw your comment today and decided to open a PR for this long-due enhancement. Not fully done yet but will be included in a future release :)
