### ISSUE TITLE
Singleton annotation is not considered in bindings

### ISSUE THREAD

**Issue by adrienlauer** [seedstack/business#39]
Business bindings (mainly done with the generic binding strategy) ignore explicit Singleton annotation on the implementation class. This annotation, if present, should be considered for all bindings.

**Comment by pith** [comment]
Not a bug. Guice scopes can only be applied on implementations (cf. [scopes](https://github.com/google/guice/wiki/Scopes#applying-scopes)).

> Guice uses annotations to identify scopes. Specify the scope for a type by applying the scope annotation to the implementation class. 

```
@RunWith(SeedITRunner.class)
public class SingletonIT {

    @ApplicationService
    static interface MyInterface {}

    @Singleton
    static class MyClass implements MyInterface {
        int x = 0;
    }

    @Inject
    private Injector injector;

    @Test
    public void testSingleton() {
        MyInterface instance = injector.getInstance(MyInterface.class);
        ((MyClass)instance).x++;
        Assertions.assertThat(((MyClass)instance).x).isEqualTo(1); // OK

        instance = injector.getInstance(MyInterface.class);
        Assertions.assertThat(((MyClass)instance).x).isEqualTo(1); // OK
    }
}
```

**Comment by adrienlauer** [comment]
The annotation was applied on implementation. It was the javax one, not the guice one. But if you wrote a test proving it works as is, it´s ok for me. I'll just double check in the project where I spotted the problem.
