### ISSUE TITLE
Provide a clean API to dynamically choose a policy implementation

### ISSUE THREAD

**Issue by pith** [seedstack/business#4]
Currently, we provide a way to choose policies implementation using qualifiers. But those qualifier are specified with annotation. The idea would be to provide an interface allowing to **programmatically choose the qualifier**.

**Proposition:**

Create an helper `Policies` like for repositories and factories.

``` java
@Inject
Policies policies;
```

Get a default implementation for a given interface.

``` java
MyPolicy myPolicy = Policies.get(MyPolicy.class)
```

Get a specific implementation by adding a qualifier.

``` java
MyPolicy myPolicy1 = Policies.get(MyPolicy.class, "qualifier-1")
```

This feature will need seedstack/seed#22

**Comment by ejemba** [comment]
This is clean :+1:

**Comment by ejemba** [comment]
By the way, policy can be dynamically create with parameters thanks to Factory. 
Typically, Policies with a parameter on its constructor. For parametrizable policies.

How does `Policies` would handle it

`MyPolicy myPolicy1 = Policies.create(MyPolicy.class, "qualifier-1").with( 7 , Time.UNIT)`

**Comment by pith** [comment]
This would not be easy to do, because this will require Guice assisted factories.

**Comment by pith** [comment]
In fact, this feature may be extended to other DDD components like services, repositories and factories by regrouping them under one entry point.

A good name would have been `DomainRegistry` but it is not really exact as service can come from the application or the interface layer. Same thing for finder.

Anyone has a better name ? Just `Registry` would be too generic...

Otherwise the API can look like this:

``` java
@Inject
DomainRegistry registry;
```

``` java
MyPolicy myPolicy = registry.policy(MyPolicy.class, "qualifier");

MyService myService = registry.service(MyService.class, "qualifier");

MyFinder myFinder = registry.service(MyFinder.class, "qualifier");

MyFactory myFactory = registry.factoryOf(MyAggregateRoot.class, "qualifier");

MyRepository myRepository = registry.repositoryOf(MyRepository.class, "qualifier");

MyAssembler myAssembler = registry.assemblerOf(MyAggregate.class, MyDto.class);
```

**Comment by pith** [comment]
Replace by seedstack/business#5
