### ISSUE TITLE
Support identity creation strategy on aggregate root factory method

### ISSUE THREAD

**Issue by pith** [seedstack/business#45]
The entities are supposed to be created by a aggregate's factory method. But in this case the identity creation mechanism won't work.

A first idea would be to add the support of the `@Create` annotation on the aggregate root method. But it would require AOP on the class which is not conceivable.

Another way might be to have the `IdentityService` in the `BaseAggregateRoot` class in a static field.

**Comment by ejemba** [comment]
@pith I don't understand the use case, that did not work 
From what I know Usually, Identity creation can be delegated to the Factory already, am I wrong ?

**Comment by Red1L** [comment]
@ejemba you're right, but it's for the case where we need to delegate identity creation for aggregate sub entities.
- Sub entities can be added after the creation of the aggregate. 
- We can't have the factory deliver sub entities also.

The best way to do that, is to add a method factory like directly in the aggregate, but there the identity management would not be take into account as it is not a factory.

**Comment by ejemba** [comment]
@Red1L I understand now thank you. 
@pith @Red1L  Can't the AggRoot propose a method which  take in input the new id + the information for the subaggregate ? 

void addOrder(String newId , String productName, Long quantity) { ... }

I also think a DomainService can handle this kind of behaviour. I mean they exist for this purpose.

**Comment by ejemba** [comment]
@pith @Red1L the following pattern is sufficient for simple case

``` java
public class Basket ... { 
    ...
    public BasketItem addBasketItem (){
        // create a basketitem , generate its identity, 
        // add it to the list of basket item
        // return it 
    }
    ....
}
```

and in a service can be used as follow.

``` java
BasketItem item = basket.addBasketItem();
// ...
basket.remove(item);
// ...
basket.update(item);
```

But the case where the identity of basket items should be managed by an external service. The identity service should be used. Problem is that Entities are not injected. 
The only solution I see is that : 
1) Either use a Domain Registry that is statically injected

``` java
IdentityService is = DomainRegistry.get(IdentityService.class)
```

2) Either make the IdentityService itself statically injected

``` java
IdentityService is = IdentityService.get()
```

this way Aggregate can access IdentityService without injection. I do not know your plan regarding DomainRegistry, but the 2) have my flavor.
@pith @Red1L your thoughs

**Comment by adrienlauer** [comment]
Maybe we can also provide basic entity services directly in BaseEntity as helpers:

```
public BasketItem addBasketItem () {
    BasketItem bi = new BasketItem();
    getIdentityService().identify(bi);
    // add it to the list of basket item
    // return it 
}
```

The same could also be done with events (`getEventService()`).

The implementation of these helpers would rely on one of the options already described above by @ejemba.

**Comment by ejemba** [comment]
@adrienlauer yes, we can think of those services as *core" domain services. 
Even If we add getIdentityService() in BaseEntity how would the method may return a reference to an IdentityService ? 
- Static fields set
- Hook on Factory and Repository that detect setIdentityService (IdentityService) pattern method on Aggregate Roots and call it with 
- `setIdentityService(IS is)` and `setEventService(ES es)` can be added in the signature of the interface `Entity` and Factory and Repo always call them anyway. 
- or "better" a generic `provideCoreService(Object service)` (name can be changed). That way only one method can be call n times. One for IdentityService and the other for EventService

there's room ....

**Comment by pith** [comment]
Will be done in #60
