### ISSUE TITLE
Exception propagation with EventHandler

### ISSUE THREAD

**Issue by Nessutbm** [seedstack/business#56]
Hi,

When coding, IDE informs developer of usage of checked exception. Then he can decide how to handle a possible exception (catch it, or throw it...).
But unchecked exception are not managed. IDE will not inform (since all line of code can throw an unchecked exception). 

This behavior encourage us to define and use checked exception, but then, EventHandler must catch it.

Currently, event system is synchronous and doesn't support checked exception. A checked exception propagation may be very useful and avoid usage of unchecked exception.

Best regards.

**Comment by Red1L** [comment]
A proper way to handle your business exceptions within an eventHandler, is to fire an event that will be in charge of handling your business exceptions, as followed :

``` java
public class MyBusinessEventHandler implements EventHandler<MyBusinessEvent> {
    @Inject
    private EventService eventService;
    @Inject
    private MyBusinessService myBusinessService;

    public void handle(MyBusinessEvent event){
        try{
            myBusinessService.doSomething();
        }catch (MyBusinessException myBusinessException){
            eventService.fire(new MyBusinessExceptionEvent());
        }
    }
}
```
