### ISSUE TITLE
DSL Assembler String and UUID

### ISSUE THREAD

**Issue by RomainBonne** [seedstack/business#58]
Hi,

When you use `UUID` as id on your Entity and String id on your representation object, you will have some limitation when you want call : 

``` java
fluentAssembler.merge(projectRepresentation).into(VehicleProject.class).fromRepository().orFail();
```

In `paramsToIds()` method (row 85) of `BaseAggAssemblerWithRepoProviderImpl` you will get an exception because classes are différents !!

Temporary solution is to modify getter in the representation to return an `UUID` object.

**Comment by pith** [comment]
This is a none limitation of the DSL. There is no transformation possible prior to the call to the factory or repository.

TODO: 
- Add this limitation to the documentation
- Look for a simple way to do this
  - Maybe something like the [ModelMapper converters](http://modelmapper.org/user-manual/converters/)
  - Or use the default factory

**Comment by adrienlauer** [comment]
Registering a converter in an customized ModelMapper assembler is enough to take this difference into account.
