### ISSUE TITLE
Pagination simplification

### ISSUE THREAD

**Issue by pith** [seedstack/business#71]
The current pagination API is really powerful but maybe to much. A little simplification to avoid line like the following could good.

```
new PaginatedView<>(new Result<>(cards, page.getCapacity(), page.getIndex()),page.getCapacity(), page.getIndex());
```

BTW the parameters order can be misleading as the order is inverted in the `Page` constructor: 

```
public Page(long pageIndex, long capacity)
```

**Comment by adrienlauer** [comment]
Done with a DSL in #92
