### ISSUE TITLE
Reintroduce Service specialization 

### ISSUE THREAD

**Issue by ejemba** [seedstack/business#76]
DomainService, ApplicationService, InterfaceServices and Infrastructure have been simplified to Service.

I think we should reintroduce the distinction as the business is a DDD implementation and those distinction effectively exist in DDD.

Being absent in the business stack those concepts are lacking for the comprehension.

The reintroduction should be discussed I think.

What do you think ?

**Comment by adrienlauer** [comment]
I don't want to force an architectural style at the framework level. By being agnostic here, clients can choose hexagonal, layered or any other architecture. 

I agree that there is value in being more expressive though, so the `@Service` annotation can now be used as a meta-annotation on custom annotations (i.e. you can create a `@DomainService` annotation, itself annotated with `@Service`).
