### ISSUE TITLE
Create a test API for the domain

### ISSUE THREAD

**Issue by adrienlauer** [seedstack/business#8]
In business test module, we should provide some annotations for overriding domain items like services, repositories, factories and so on with mockups or loopbacks. 

This can already be done by defining overriding bindings but an API could definitely be sweeter for our clients.

Something like:

```
@TestRepository
public class CustomerRepositoryMock implements CustomerRepository { ... }
```

The CustomerRepositoryMock would override the corresponding repository binding in tests. The qualified bindings should also be supported.

**Comment by pith** [comment]
After some tests and improvements, we might use the `InMemoryRepository` (moved in the unit tests #27) for this.

**Comment by adrienlauer** [comment]
Done in 743d127054e4007fd75033075b8a6e189e29b860 with `@Surrogate` annotation.
